[package]
name = "rust-audio-analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
minimp3 = "0.6.1"
rustfft = "6.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
